config/routes.rb
Rails.application.routes.draw do

    ## Resources Route 
        resources :users, 
            path: '/'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

	## establecemos los parametros para el campo type_person
	enum type_person: {
	    natural: "Natural",
	    jurídica: "Jurídica"
  	}

  	## validaciones
		validates :type_person, presence: true

		validates :identification, presence: true

		validates :name, 
				presence: true, 
				length: { in: 3..35 },
				format: {
					with:  /\A[a-zA-Z\u00C0-\u017F\s]+\z/
				}

		validates :email, 
			presence: true, 
			format: { 
				with: /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+\z/
	 		} 

		validates :tlf, 
			presence: true,
			format: {
				with: /(0414|0424|0412|0416|0426)[0-9]{7}/
			}

	# validates :tlf_second,
		# format: {
		# 	with: /(0414|0424|0412|0416|0426)[0-9]{7}/ 
		# }

  		validates :emit, presence: true
  		validates :expiration, presence: true
  		validate :validate_not_future # ---> Validation date NOT future

	before_save :capitalize_attributes

	private
		## formatiamos los atributos
			def capitalize_attributes
				self.name = name.titleize
				self.email = email.downcase
			end
		## validamos las fechas ingresadas future or past
			def validate_not_future
				if emit.present? && emit.future?
					errors.add(:emit, "can't be in the future")
				end
				if expiration.present? && expiration.past?
					errors.add(:expiration, "can't be in the future")
				end


			# -------------------------------

				## BUSCAR COMO VALIDAR DESDE LA FUNCION ##
				# if type_person.present? && type_person == 'natural'
				# 	validates :identification, presence: true
				# end

			# -------------------------------



		end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pagy::Backend

	around_action :switch_locale
	before_action :turbo_frame_request_variant

	private
		## funcionabilidad del search en el index con turbo
			def turbo_frame_request_variant
				request.variant = :turbo_frame if turbo_frame_request?
			end
		
		## funcionabilidad de las traducciones
			def switch_locale( &action )
				I18n.with_locale( locale_from_header, &action )
			end

			def locale_from_header
				request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		## params :query filtra los elementos por busqueda ingresada
		## pagy para la paginacion next previus
			if params[:query].present?
				@pagy, @users = pagy(User.where("name like ?", "%#{params[:query]}%").order('id ASC'), items: 5)
			else
				@pagy, @users = pagy(User.all.order('id ASC'), items: 5)
			end
	end

	def show
		user
	end

	def new
		@user = User.new(request_params)
	end

	def create
		## guardamos, redireccionamos y mandamos notificación
			@user = User.new(request_params)

			if @user.save
				redirect_to users_path, 
					notice: t('notice.user_regist')
			else
				render :new, 
					status: :unprocessable_entity
			end	
	end

	def edit
		user 
	end

	def update
		## actualizamos, redireccionamos y mandamos notificación. En caso contrario mandamos error para mostrar las validaciones
			if user.update( request_params )
				redirect_to users_path, 
					notice: t('notice.user_update')
			else
				render :edit, 
					status: :unprocessable_entity
			end
	end

	def destroy
		## eliminamos, redireccionamos y mandamos notificación.
			user.destroy
			redirect_to users_path, 
				notice: t('notice.user_delet'), 
				status: :see_other
	end

	private
		def user
			## refactorizamos para reutilizar codigo
				@user = User.find( params[ :id ] )
		end

		def request_params
			## establecemos los parametros permitidos en los requests
				params.require( :user ).permit( 
					:account_type, 
					:type_person, 
					:identification, 
					:name, 
					:email, 
					:tlf, 
					:tlf_second, 
					:emit, 
					:expiration 
				) rescue{}
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>SiscoBank | <%= t( 'common.title2' ) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>

<body class="bg-gray-200">
    <%= render 'partials/erros_flash' %>
    <%= render 'partials/header' %>
    <%= yield %>
</body>
</html>

app/views/partials/_erros_flash.html.erb
<% if alert || notice %>
	<% color = alert ? 'bg-red-400' : 'bg-green-400' %>
	<div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
		<div class="flex flex-col items-end space-y-4">
			<div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
				<div class="p-2">
					<div class="flex items-start">
						<div class="ml-3 w-0 flex-1 pt-0.5">
							<p class="text-sm leading-5 font-medium">
								<%= alert || notice %>
							</p>
						</div>
						<div class="ml-4 flex-shrink-0 flex">
							<button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
								<svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
									<path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
								</svg>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/partials/_header.html.erb
<div class="bg-white flex justify-between items-center p-2">
	<%= link_to users_path do %>
		<h1 class="text-2xl font-bold text-blue-500 hover:text-blue-400">Sisco Bank C.A</h1>
	<% end %>

	<div>
		<%= link_to t('common.new_user'), new_user_path, class: "mx-2 text-blue-500 font-bold hover:text-blue-400" %>
	</div>
</div>

app/views/users/_form_partial.html.erb
<div class="min-h-screen flex flex-col items-center justify-center bg-gray-100">
	<div class="flex flex-col bg-white shadow-md px-4 sm:px-6 md:px-8 lg:px-10 py-8 rounded-3xl w-50 max-w-md">
		<div class="font-medium self-center text-xl sm:text-3xl text-gray-800">
			<% if ( @user.name? ) %>
				<%= t('common.edit_users') %>
			<% else %>
				<%= t('common.new_user') %>
			<% end %>
		</div>

		<div class="mt-5">
			<%= form_with model: @user do | form | %>
				<%= turbo_frame_tag "type_person", data: { controller: "navigate" } do %>
					<div class="flex flex-wrap mb-3">
						<div class="flex items-center mr-4">
					        <%= form.radio_button :type_person, 'natural', data: { action: 'change->navigate#to', url: new_user_path({ user: { type_person: 'natural' } }) }, class: "w-4 h-4 text-red-600 bg-gray-100 border-gray-300 focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600", id: 'natural'%>
					        <label for="natural" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"><%= t('common.person') %> Natural</label>
						</div>
						<div class="flex items-center mr-4">
					        <%= form.radio_button :type_person, 'jurídica', data: { action: 'change->navigate#to', url: new_user_path({ user: { type_person: 'jurídica' } }) }, class: "w-4 h-4 text-green-600 bg-gray-100 border-gray-300 focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600", id: 'jurídica'%>
					        <label for="jurídica" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"><%= t('common.person') %> Juridica</label>
						</div>
						<% @user.errors.full_messages_for(:type_person).each do | error_message | %>
							<%= error_message %>.
						<% end %>
					</div>

				    <% if @user.natural? %>
	    				<div class="flex flex-col mb-3">
							<div class="relative">
								<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
									<i class="fa fa-id-card text-blue-500"></i>
								</div>
								<%= form.text_field :identification, placeholder: t('common.identification'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
							</div>
							<% @user.errors.full_messages_for(:identification).each do | error_message | %>
								<%= error_message %>.
							<% end %>
						</div>

						<div class="flex flex-col mb-3">
							<div class="relative">
								<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
									<i class="fa fa-user text-blue-500"></i>
								</div>
								<%= form.text_field :name, placeholder: t('common.name'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
							</div>
							<% @user.errors.full_messages_for(:name).each do | error_message | %>
								<%= error_message %>.
							<% end %>
						</div>

						<hr class="mt-3 mb-3">
				    <% end %>

		    	    <% if @user.jurídica? %>
	    				<div class="flex flex-col mb-3">
							<div class="relative">
								<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
									<i class="fa fa-id-card text-blue-500"></i>
								</div>
								<%= form.text_field :identification, placeholder: t('common.rif'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
							</div>
							<% @user.errors.full_messages_for(:identification).each do | error_message | %>
								<%= error_message %>.
							<% end %>
						</div>

						<div class="flex flex-col mb-3">
							<div class="relative">
								<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
									<i class="fa fa-building text-blue-500"></i>
								</div>
								<%= form.text_field :name, placeholder: t('common.reason'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
							</div>
							<% @user.errors.full_messages_for(:name).each do | error_message | %>
								<%= error_message %>.
							<% end %>
						</div>
						<hr class="mt-3 mb-3">
				    <% end %>
				<% end %>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-at text-blue-500"></i>
						</div>
						<%= form.text_field :email, placeholder: t('common.email'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
					</div>
					<% @user.errors.full_messages_for(:email).each do | error_message | %>
						<%= error_message %>.
					<% end %>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-phone text-blue-500"></i>
						</div>
						<%= form.text_field :tlf, placeholder: t('common.tlf'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
					</div>
					<% @user.errors.full_messages_for(:tlf).each do | error_message | %>
						<%= error_message %>.
					<% end %>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-phone text-blue-500"></i>
						</div>
						<%= form.text_field :tlf_second, placeholder: t('common.tlf_second'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
					</div>
					<% @user.errors.full_messages_for(:tlf_second).each do | error_message | %>
						<%= error_message %>.
					<% end %>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-calendar text-blue-500"></i>
						</div>
						<%= form.date_field :emit, max: Date.today, placeholder: t('common.emit'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
					</div>
					<% @user.errors.full_messages_for(:emit).each do | error_message | %>
						<%= error_message %>.
					<% end %>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-calendar text-blue-500" aria-hidden="true"></i>

						</div>
						<%= form.date_field :expiration, min: Date.today, placeholder: t('common.expired'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" %>
					</div>
					<% @user.errors.full_messages_for(:expiration).each do | error_message | %>
						<%= error_message %>.
					<% end %>
				</div>
				<hr>
				<div class="flex w-full">
					<%= form.submit t('common.save'), class: "flex mt-2 items-center justify-center focus:outline-none text-white text-sm sm:text-base bg-blue-500 hover:bg-blue-600 rounded-2xl py-2 w-full transition duration-150 ease-in"%>

					<%= link_to t('common.cancel'), users_path, class: "flex mt-2 ml-3 items-center justify-center focus:outline-none text-white text-sm sm:text-base bg-red-500 hover:bg-red-600 rounded-2xl py-2 w-full transition duration-150 ease-in"%>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_user.html.erb
<tr id="<%= dom_id user %>" class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <td class="px-6 py-4"><%= user.type_person&.titleize %></td>
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= user.name %></th>
    <td class="px-6 py-4"><%= user.identification %></td>
    <td class="px-6 py-4"><%= user.tlf %></td>
    <td class="px-6 py-4">
        <%= link_to t('common.see'), user, class: 'user font-medium text-blue-600 dark:text-blue-500 hover:underline' %>
    </td>
</tr>

app/views/users/_users.html.erb
<%= turbo_frame_tag "users" do %>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.type2') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.description') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.ident') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.tlf') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.action') %>
                </th>
            </tr>
        </thead>
        <tbody>
            <%= render users %>  
        </tbody>      
    </table>
<% end %>

app/views/users/edit.html.erb
<%= render 'form_partial' %>

app/views/users/index.html+turbo_frame.erb
<%= turbo_frame_tag "users" do %>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.type2') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.description') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.ident') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.tlf') %>
                </th>
                <th scope="col" class="px-6 py-3">
                    <%= t('common.action') %>
                </th>
            </tr>
        </thead>
        <tbody>
            <%= render @users %>
        </tbody>      
    </table>
<% end %>

app/views/users/index.html.erb
<div class="min-h-screen bg-gray-100 p-10">
	<div class="relative overflow-x-auto shadow-md sm:rounded-lg bg-white shadow-md px-4 sm:pr-6 lg:px-10 pb-6 pt-4 rounded-3xl w-50">
	    <div class="pb-4 bg-white dark:bg-gray-900 flex justify-end">
			<%= form_with(url: users_path, method: "GET", data: { controller: "form-submission", turbo_frame: "users", turbo_action: "advance" }) do |form| %>
				<%= form.label :query, 'Search', class: 'sr-only', for: 'table-search' %>
		        <div class="relative mt-1">
		            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
		                <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
		            </div>
    				<%= form.text_field :query, data: { action: "input->form-submission#search" }, class: 'block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', placeholder: t('common.search'), id: 'table-search' %>
		        </div>
			<% end %>
	    </div>
	    <hr class="mb-4">
        
        <%= render "users", users: @users %>

        <% if ( @pagy.prev != nil ) %>
			<nav class="text-right mt-4" aria-label="Page navigation example">
				<% if @pagy.prev %>
			        <%= link_to t('common.prev'), users_path(page: @pagy.prev), class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-600 bg-white border border-gray-400 rounded-lg hover:bg-gray-200 hover:text-gray-700' %>
				<% else %>
			      	<%= button_tag t('common.prev'), class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-300 bg-white border border-gray-300 rounded-lg  :text-white', disabled: true %>
				<% end %>

				<% if @pagy.next %>
			        <%= link_to t('common.next'), users_path(page: @pagy.next), class: 'inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-gray-600 bg-white border border-gray-400 rounded-lg hover:bg-gray-200 hover:text-gray-700' %>
				<% else %>
			  		<%= button_tag t('common.next'), class: 'inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-gray-300 bg-white border border-gray-300 rounded-lg  :text-white', disabled: true %>
				<% end %>
			</nav>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<%= render 'form_partial' %>

app/views/users/show.html.erb
<div class="min-h-screen flex flex-col items-center justify-center bg-gray-100">
	<div class="flex flex-col bg-white shadow-md px-4 sm:px-6 md:px-8 lg:px-10 py-8 rounded-3xl w-50 max-w-md">
		<div class="font-medium self-center text-xl sm:text-3xl text-gray-800">
			<%= t( 'common.details_user' ) %>
		</div>

		<div class="mt-5">
			<%= form_with model: @user do | form | %>
				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-tag text-blue-500"></i>
						</div>
						<input type="text" class="text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" disabled value="<%= @user.type_person.titleize %>">
					</div>
				</div>
				
				<hr class="mb-3">

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-id-card text-blue-500"></i>
						</div>
						<%= form.text_field :identification, placeholder: t('common.rif'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
					</div>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<% if ( @user.type_person == 'natural' ) %>
								<i class="fa fa-user text-blue-500"></i>
							<% else %>
								<i class="fa fa-building text-blue-500"></i>
							<% end %>
						</div>
						<%= form.text_field :name, placeholder: t('common.reason'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
					</div>
				</div>
				<hr class="mt-3 mb-3">

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-at text-blue-500"></i>
						</div>
						<%= form.text_field :email, placeholder: t('common.email'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
					</div>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-phone text-blue-500"></i>
						</div>
						<%= form.text_field :tlf, placeholder: t('common.tlf'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
					</div>
				</div>

				<% if ( @user.tlf_second? ) %>
					<div class="flex flex-col mb-3">
						<div class="relative">
							<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
								<i class="fa fa-phone text-blue-500"></i>
							</div>
							<%= form.text_field :tlf_second, placeholder: t('common.tlf_second'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
						</div>
					</div>
				<% end %>
		
				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-calendar text-blue-500"></i>
						</div>
						<%= form.date_field :emit, max: Date.today, placeholder: t('common.emit'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
					</div>
				</div>

				<div class="flex flex-col mb-3">
					<div class="relative">
						<div class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400">
							<i class="fa fa-calendar text-blue-500" aria-hidden="true"></i>
						</div>
						<%= form.date_field :expiration, min: Date.today, placeholder: t('common.expired'), class: "text-sm placeholder-gray-500 pl-10 pr-4 rounded border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400", disabled: true %>
					</div>
				</div>
				<hr>
				<div class="flex w-full mt-2">
					<%= link_to t('common.edit_user'), edit_user_path( @user ), class: "flex mt-2 items-center justify-center focus:outline-none text-white text-sm sm:text-base bg-blue-500 hover:bg-blue-600 rounded-2xl py-2 w-full transition duration-150 ease-in"%>

					<%= link_to t('common.delete'), user_path( @user ), class: "flex mt-2 ml-3 items-center justify-center focus:outline-none text-white text-sm sm:text-base bg-red-500 hover:bg-red-600 rounded-2xl py-2 w-full transition duration-150 ease-in", data: {
						turbo_method: :delete,
						turbo_confirm: t('common.confirm_delet')
					}%>
				</div>
			<% end %>
		</div>
	</div>
</div>